const AppData = {
  Makhachkala: {
    city: "Махачкала",
    places: [
      {
        name: "Donutsday",
        rating: 4.5,
        reviews: 82,
        price_category: "средняя",
        pluses: ["пончики", "кофе с собой", "Wi‑Fi"],
        address: "ул. Буйнакского, 4",
      },
      {
        name: "Кофевар",
        rating: 4.9,
        reviews: 40,
        price_category: "средняя",
        pluses: ["кофе с собой", "чай", "какао"],
        address: "просп. Гамидова, 71",
      },
      {
        name: "Family",
        rating: 4.8,
        reviews: 131,
        price_category: "эконом",
        pluses: ["пицца", "детское меню", "кофе с собой"],
        address: "ш. Карабудахкентское, 11",
      },
      {
        name: "Rafaello",
        rating: 4.7,
        reviews: 193,
        price_category: "средняя",
        pluses: ["кондитерские изделия", "Wi-Fi", "кофе с собой"],
        address: "ул. Гагарина, 80/1",
      },
      {
        name: "1930 Coffee Company",
        rating: 4.9,
        reviews: 686,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "ноутбук"],
        address: "ул. Ермошкина, 11/13",
      },
      {
        name: "Nuteo",
        rating: 4.8,
        reviews: 603,
        price_category: "средняя",
        pluses: ["завтраки", "кофе с собой"],
        address: "пр. Расула Гамзатова, 4",
      },
      {
        name: "Marsha",
        rating: 4.8,
        reviews: 502,
        price_category: "средняя",
        pluses: ["ПП-завтраки", "рабочая зона", "кофе с собой"],
        address: "ул. Гаруна Курбанова, 21",
      },
      {
        name: "Fabrista",
        rating: 5.0,
        reviews: 381,
        price_category: "эконом",
        pluses: ["лимонады", "выпечка", "кофе с собой"],
        address: "ул. Дахадаева, 22",
      },
      {
        name: "Wall Street",
        rating: 4.6,
        reviews: 212,
        price_category: "премиум",
        pluses: ["бизнес-ланч", "Wi-Fi", "кофе с собой"],
        address: "ул. Даниялова, 62",
      },
      {
        name: "BRANDCOFFEE",
        rating: 4.7,
        reviews: 97,
        price_category: "эконом",
        pluses: ["крафтовые пончики", "баттлы", "кофе с собой"],
        address: "ул. Ирчи Казака, 56/1",
      },
      {
        name: "Twins",
        rating: 4.4,
        reviews: 81,
        price_category: "средняя",
        pluses: ["бургеры", "вафли", "кофе с собой"],
        address: "пр. Гамидова, 24А",
      },
      {
        name: "And Coffee",
        rating: 4.7,
        reviews: 81,
        price_category: "эконом",
        pluses: ["bubble tea", "рабочая зона", "кофе с собой"],
        address: "ул. Ирчи Казака, 56/1",
      },
      {
        name: "Publico",
        rating: 4.8,
        reviews: 58,
        price_category: "средняя",
        pluses: ["выпечка", "уютная атмосфера"],
        address: "ул. Ахмата-Хаджи Кадырова, 23А",
      },
      {
        name: "Lusan",
        rating: 4.9,
        reviews: 49,
        price_category: "премиум",
        pluses: ["авторские десерты", "уют"],
        address: "ул. Октябрьская, 115",
      },
      {
        name: "Наполеонофф",
        rating: 4.9,
        reviews: 52,
        price_category: "премиум",
        pluses: ["эклеры", "Wi-Fi", "кофе с собой"],
        address: "ул. Батырая, 21",
      },
      {
        name: "Pekarius",
        rating: 4.5,
        reviews: 124,
        price_category: "средняя",
        pluses: ["выпечка", "завтраки", "кофе с собой"],
        address: "пр. Имама Шамиля, 29",
      },
    ],
  },
  Taganrog: {
    city: "Таганрог",
    places: [
      {
        name: "Old School Coffee",
        rating: 5.0,
        reviews: 105,
        price_category: "средняя",
        pluses: ["завтраки", "кофе навынос", "Wi-Fi", "уютная атмосфера"],
        address: "ул. Петровская, 53",
      },
      {
        name: "Coffee Like",
        rating: 4.8,
        reviews: 54,
        price_category: "эконом",
        pluses: ["кофе навынос", "круглосуточно"],
        address: "ул. Петровская, 37",
      },
      {
        name: "Свежее зерно",
        rating: 4.7,
        reviews: 125,
        price_category: "средняя",
        pluses: ["завтраки", "бизнес-ланч", "Wi-Fi", "ноутбук"],
        address: "ул. Петровская, 98",
      },
      {
        name: "Secret Spot",
        rating: 4.5,
        reviews: 35,
        price_category: "средняя",
        pluses: ["завтраки", "кофе с собой", "столики на улице"],
        address: "Тургеневский пер., 10/49",
      },
      {
        name: "Liberica Coffee",
        rating: 4.1,
        reviews: 46,
        price_category: "средняя",
        pluses: ["кофе с собой", "смузи", "молочные коктейли"],
        address: "Инструментальная ул., 15в",
      },
    ],
  },
  RostovOnDon: {
    city: "Ростов-на-Дону",
    places: [
      {
        name: "Sample Coffee",
        rating: 4.9,
        reviews: 1099,
        price_category: "средняя",
        pluses: ["завтраки", "вафли", "Wi-Fi", "кофе с собой"],
        address: "ул. Пушкинская, 204",
      },
      {
        name: "Sample Coffee",
        rating: 4.9,
        reviews: 84,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "салаты", "кофе с собой"],
        address: "просп. Кировский, 57",
      },
      {
        name: "Ванлав",
        rating: 4.9,
        reviews: 290,
        price_category: "средняя",
        pluses: ["кондитерская", "Wi-Fi", "кофе с собой"],
        address: "ул. Ларина, 45",
      },
      {
        name: "Surf Coffee",
        rating: 4.7,
        reviews: 302,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "кофе с собой"],
        address: "Большая Садовая ул., 81",
      },
      {
        name: "Surf Coffee x Tower",
        rating: 4.7,
        reviews: 97,
        price_category: "средняя",
        pluses: ["пончики", "смузи", "кофе с собой"],
        address: "просп. Будённовский, 95",
      },
      {
        name: "Пекули",
        rating: 4.8,
        reviews: 61,
        price_category: "средняя",
        pluses: ["пончики", "вафли", "кофе с собой"],
        address: "ул. Сержантова, 6",
      },
      {
        name: "CoffeeMan",
        rating: 4.7,
        reviews: 121,
        price_category: "средняя",
        pluses: ["блины", "салаты", "Wi-Fi", "кофе с собой"],
        address: "ул. Пушкинская, 74",
      },
      {
        name: "GelaTiamo",
        rating: 4.7,
        reviews: 47,
        price_category: "средняя",
        pluses: ["кофе с собой", "молочные коктейли"],
        address: "ул. Пушкинская, 197",
      },
      {
        name: "Крэк",
        rating: 4.0,
        reviews: 73,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "выпечка", "кофе с собой"],
        address: "ул. Большая Садовая, 57",
      },
      {
        name: "Крэк",
        rating: 4.1,
        reviews: 66,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "сэндвичи"],
        address: "просп. Чехова, 31",
      },
      {
        name: "Крэк",
        rating: 4.1,
        reviews: 40,
        price_category: "средняя",
        pluses: ["супы", "сэндвичи", "кофе с собой"],
        address: "просп. Будённовский, 52",
      },
      {
        name: "Star's Coffee",
        rating: 3.8,
        reviews: 70,
        price_category: "средняя",
        pluses: ["Wi-Fi", "сэндвичи"],
        address: "ул. Большая Садовая, 81",
      },
      {
        name: "Кекс",
        rating: 3.3,
        reviews: 89,
        price_category: "эконом",
        pluses: ["салаты", "сэндвичи", "работа с ноутбуком"],
        address: "пер. Соборный, 21",
      },
      {
        name: "Арфе",
        rating: 4.7,
        reviews: 45,
        price_category: "средняя",
        pluses: ["Wi-Fi", "кофе и чай"],
        address: "ул. Шаумяна, 5",
      },
      {
        name: "Sample Coffee",
        rating: 4.8,
        reviews: 48,
        price_category: "средняя",
        pluses: ["завтраки", "вафли", "кофе с собой"],
        address: "просп. Крепостной, 76",
      },
    ],
  },
  Derbent: {
    city: "Дербент",
    places: [
      {
        name: "Ванлав",
        rating: 5.0,
        reviews: 212,
        price_category: "средняя",
        pluses: ["кондитерская", "кофе с собой", "доставка"],
        address: "ул. Курбанова, 31",
      },
      {
        name: "Surf Coffee x Pearl",
        rating: 4.8,
        reviews: 113,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "соки", "молочные коктейли"],
        address: "ул. Курбанова, 31",
      },
      {
        name: "Марша",
        rating: 4.7,
        reviews: 37,
        price_category: "средняя",
        pluses: ["салаты", "боулы", "кофе с собой"],
        address: "ул. Гейдара Алиева, 11в",
      },
      {
        name: "Сова",
        rating: 4.9,
        reviews: 32,
        price_category: "средняя",
        pluses: ["сэндвичи", "молочные коктейли", "кофе с собой"],
        address: "ул. Таги-Заде, 78",
      },
      {
        name: "Chi Coffe",
        rating: 4.5,
        reviews: 58,
        price_category: "средняя",
        pluses: ["завтраки", "вафли", "Wi-Fi", "кофе с собой"],
        address: "ул. Таги-Заде, 30Б",
      },
      {
        name: "Donutsday",
        rating: 3.9,
        reviews: 40,
        price_category: "средняя",
        pluses: ["пончики", "молочные коктейли", "кофе с собой"],
        address: "ул. Буйнакского, 29",
      },
      {
        name: "ZM Culture & Coffee",
        rating: 4.1,
        reviews: 114,
        price_category: "средняя",
        pluses: ["бизнес-ланч", "бургеры", "кофе с собой"],
        address: "ул. Гагарина, 12",
      },
      {
        name: "Ficus",
        rating: 4.8,
        reviews: 40,
        price_category: "средняя",
        pluses: ["завтраки", "комплексные блюда", "Wi-Fi"],
        address: "ул. Гейдара Алиева, 11",
      },
      {
        name: "Avocado",
        rating: 4.8,
        reviews: 37,
        price_category: "средняя",
        pluses: ["кофе с собой", "смуди", "ноутбук"],
        address: "ул. Буйнакского, 68Б",
      },
      {
        name: "Alhimik",
        rating: 4.3,
        reviews: 36,
        price_category: "средняя",
        pluses: ["ланч", "выпечка", "кофе с собой"],
        address: "просп. Агасиева, 17а/2",
      },
      {
        name: "Nur Travel Coffee",
        rating: 5.0,
        reviews: 36,
        price_category: "средняя",
        pluses: ["кофе с собой", "глинтвейн", "смузи", "доставка"],
        address: "7-й Магал, 15а",
      },
      {
        name: "Bloom",
        rating: 3.9,
        reviews: 34,
        price_category: "средняя",
        pluses: ["завтраки", "Wi-Fi", "коктейли"],
        address: "просп. Агасиева, 35и",
      },
      {
        name: "17Bar Coffee",
        rating: 4.7,
        reviews: 37,
        price_category: "средняя",
        pluses: ["ноутбук", "молочные коктейли", "кофе с собой"],
        address: "ул. Канделаки, 17",
      },
    ],
  },
};

export { AppData };
